--- 
- name: Upgrade existing OCP 4.16 cluster to 4.17 
  hosts: localhost 
  connection: local 
  gather_facts: False 

  vars:
    openshift_admin_password: "{{ xtra_openshift_admin_password }}"
    openshift_admin_username: "{{ xtra_openshift_admin_username }}"

  tasks:
    - name: Get OpenShift token
      redhat.openshift.openshift_auth: 
        username: "{{ openshift_admin_username }}"
        password: "{{ openshift_admin_password }}"
        host: "{{ xtra_openshift_api }}"
        verify_ssl: False 
      register: openshift_auth_results

    - name: Login with oc 
      ansible.builtin.shell: oc login --token={{ openshift_auth_results.openshift_auth.api_key }} --server={{ xtra_openshift_api }} --insecure-skip-tls-verify
      register: login 

    - name: Check if upgrade is available 
      ansible.builtin.shell: oc adm upgrade 
      register: upgradeable 

    - name: Get ClusterVersion config object
      kubernetes.core.k8s_info:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        kind: ClusterVersion
        host: "{{ xtra_openshift_api }}"
        verify_ssl: False 
      register: cluster_version 

    - name: Get subscription information 
      kubernetes.core.k8s_info:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        api: operators.coreos.com/v1alpha1
        kind: Subscription
        namespace: openshift-operators-redhat
        host: "{{ xtra_openshift_api }}"
        label_selectors:
          - operators.coreos.com/elasticsearch-operator.openshift-operators-redhat
        verify_ssl: False 
      register: elastic_subscription

    - debug:
        var: elastic_subscription.resources[0].spec.startingCSV 

    # - name: Get current subscription information for elasticsearch 
    #   ansible.builtin.shell: oc get subscription.operators.coreos.com elasticsearch-operator -n openshift-operators-redhat -o yaml | grep currentCSV
    #   register: currentCSV

    - name: Remove incompatible elasticsearch operator if present for upgrade 
      block:   
          
        - name: Delete the subscription 
          ansible.builtin.shell: oc delete subscription.operators.coreos.com elasticsearch-operator -n openshift-operators-redhat 

        - name: Delete the CSV 
          ansible.builtin.shell: oc delete clusterserviceversion {{ elastic_subscription.resources[0].spec.startingCSV }} -n openshift-operators-redhat 
      when: elastic_subscription.resources[0].spec.startingCSV is defined 

    - name: Set upgrade channel 
      ansible.builtin.shell: oc adm upgrade channel stable-4.17 

    - name: Start Cluster Upgrade 
      ansible.builtin.shell: oc adm upgrade --to-latest=true


    #   block:
    #   - name: Get token for login 
    #     redhat.openshift.openshift_auth: 
    #       username: "{{ openshift_admin_username }}"
    #       password: "{{ openshift_admin_password }}"
    #       host: "{{ xtra_openshift_api }}"
    #       verify_ssl: False 
    #     register: openshift_auth_results

    #   - name: Get ClusterVersion config object
    #     kubernetes.core.k8s_info:
    #       api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
    #       kind: ClusterVersion
    #       host: "{{ xtra_openshift_api }}"
    #       verify_ssl: False 
    #     register: cluster_version 

    #   - debug:
    #       var: cluster_version